---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: English
- type: directory
  path: content/english/home
  label: Homepage
  create: documents
  match: "*"
  templates:
  - homepage-hero-section
  - visual-left-section
  - visual-right-section
  - full-width-section
  - home-section
- type: directory
  path: content/english/post
  label: Pages
  create: all
  match: "*"
  templates:
  - page
- type: heading
  label: German
- type: directory
  path: content/german/home
  label: Homepage
  create: documents
  match: "*"
  templates:
  - homepage-hero-section
  - text-left-side-section
  - full-width-section
  - visual-left-section
  - visual-right-section
  - home-section
- type: directory
  path: content/german/post
  label: Pages
  create: all
  match: "*"
  templates:
  - page
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.63.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:node10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
